const swaggerAutogen = require('swagger-autogen')()
const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    definitions: {
        Brand: {
            type: "object",
            properties: {
                $name: {
                    type: "string",
                    example: "Apple"
                }
            },
            required: ["name"]
        },
        Category: {
            type: "object",
            properties: {
                $name: {
                    type: "string",
                    example: "Watches"
                }
            },
            required: ["name"]
        },
        Product: {
            type: "object",
            properties: {
                $name: {
                    type: "string",
                    example: "Apple-x"
                }
            },
            required: ["name"]
        },
    }
}

/*    Category: {
            $Name: "Watch"
        },
        Product: {
            $Name: "Xmas star",
            $description: "Gold",
            $imageUrl: "https://www.instagram.com/",
            $unitPrice: "15.34e",
            $stock: "10",
            $brandId: "23",
            $categoryId: "11"
        },
        User: {
            $firstname: 'Adam',
            $lastname: 'Support',
            $username: 'admin',
            $password: "testpasS1",
            $email: 'admin@noroff.no',
            $adress: 'Online',
            $phone: 911
        },
    } */
const outputFile = './swagger-output.json'
const endpointsFiles = ['./app.js']

swaggerAutogen(outputFile, endpointsFiles, doc);